---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    #  KAFKA_LOG_CLEANUP_POLICY: delete

  init-kafka:
    image: confluentinc/cp-kafka:7.0.1
    volumes:
      - ${PWD}/sample.txt:/sample.txt:ro
    depends_on:
      - broker
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server broker:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic data-input --partitions 10
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic data-output --partitions 1


      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server broker:29092 --list

      echo -e 'Describing topic data-input:'
      kafka-topics --bootstrap-server=broker:29092 --describe --topic data-input
      "

  producer:
    image: confluentinc/cp-kafkacat
    container_name: sender
    depends_on:
      - init-kafka
      - broker
    volumes:
      - ${PWD}/sample.txt:/sample.txt
    entrypoint: [ '/bin/sh', '-c' ]
    command:  |
      "
      cat /sample.txt | kafkacat -b broker:29092 -t data-input -P -K: -p 0
      cat /sample.txt | kafkacat -b broker:29092 -t data-input -P -K: -p 1
      cat /sample.txt | kafkacat -b broker:29092 -t data-input -P -K: -p 2
      cat /sample.txt | kafkacat -b broker:29092 -t data-input -P -K: -p 3
      cat /sample.txt | kafkacat -b broker:29092 -t data-input -P -K: -p 4
      cat /sample.txt | kafkacat -b broker:29092 -t data-input -P -K: -p 5
      cat /sample.txt | kafkacat -b broker:29092 -t data-input -P -K: -p 6
      cat /sample.txt | kafkacat -b broker:29092 -t data-input -P -K: -p 7
      cat /sample.txt | kafkacat -b broker:29092 -t data-input -P -K: -p 8
      cat /sample.txt | kafkacat -b broker:29092 -t data-input -P -K: -p 9
      "

      